services:
  keycloak:
    build: ./keycloak
    container_name: instaff-keycloak
    ports:
      - "8081:8080"
    #volumes:
     # - ./keycloak/themes:/opt/keycloak/themes
    depends_on:
      - mailhog

  mailhog:
    build: ./mailhog
    container_name: instaff-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  postgres:
    container_name: instaff-postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo

volumes:
  postgres:

